# Generated by Django 4.1.13 on 2026-03-07 04:58

from django.db import migrations
from django.utils import timezone


def backfill_approved(apps, schema_editor):
    """Mark all existing donors as approved so they are not locked out."""
    Donor = apps.get_model('donor', 'Donor')
    now = timezone.now()
    Donor.objects.filter(is_approved=False).update(is_approved=True, approved_at=now)


def reverse_backfill(apps, schema_editor):
    pass  # No-op reverse


class Migration(migrations.Migration):

    dependencies = [
        ('donor', '0007_donor_aadhaar_number_donor_approved_at_and_more'),
    ]

    operations = [
        migrations.RunPython(backfill_approved, reverse_backfill),
    ]
