# Generated by Django 4.1.13 on 2026-03-07 04:57

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('donor', '0006_backfill_last_donated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='donor',
            name='aadhaar_number',
            field=models.CharField(default='', help_text='12-digit Aadhaar number', max_length=12, validators=[django.core.validators.RegexValidator(message='Aadhaar number must be exactly 12 digits.', regex='^\\d{12}$')]),
        ),
        migrations.AddField(
            model_name='donor',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='donor',
            name='is_approved',
            field=models.BooleanField(default=False, help_text='Admin must approve before account is active'),
        ),
        migrations.AddField(
            model_name='donor',
            name='rejection_reason',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.CreateModel(
            name='MedicalReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document', models.FileField(help_text='Upload medical health report (PDF, JPG, PNG, DOC, etc.)', upload_to='medical_reports/donor/%Y/%m/')),
                ('document_name', models.CharField(blank=True, max_length=255)),
                ('notes', models.CharField(blank=True, help_text='Optional notes about this report', max_length=500)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('is_verified', models.BooleanField(default=False, help_text='Admin verified this report')),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('donor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='donor.donor')),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_donor_reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Medical Report',
                'verbose_name_plural': 'Medical Reports',
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
