# Generated by Django 4.1.13 on 2026-03-07 04:57

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='aadhaar_number',
            field=models.CharField(default='', help_text='12-digit Aadhaar number', max_length=12, validators=[django.core.validators.RegexValidator(message='Aadhaar number must be exactly 12 digits.', regex='^\\d{12}$')]),
        ),
        migrations.AddField(
            model_name='patient',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='doctor_prescription',
            field=models.FileField(blank=True, help_text='Upload doctor prescription (PDF, JPG, PNG, DOC, etc.)', null=True, upload_to='prescriptions/patient/%Y/%m/'),
        ),
        migrations.AddField(
            model_name='patient',
            name='is_approved',
            field=models.BooleanField(default=False, help_text='Admin must approve before account is active'),
        ),
        migrations.AddField(
            model_name='patient',
            name='rejection_reason',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
