# Generated by Django 4.1.13 on 2026-03-07 04:58

from django.db import migrations
from django.utils import timezone


def backfill_approved(apps, schema_editor):
    """Mark all existing patients as approved so they are not locked out."""
    Patient = apps.get_model('patient', 'Patient')
    now = timezone.now()
    Patient.objects.filter(is_approved=False).update(is_approved=True, approved_at=now)


def reverse_backfill(apps, schema_editor):
    pass  # No-op reverse


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0002_patient_aadhaar_number_patient_approved_at_and_more'),
    ]

    operations = [
        migrations.RunPython(backfill_approved, reverse_backfill),
    ]
