"""
Django settings for BloodBridge project.

Generated by 'django-admin startproject' using Django 4.2.7.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

from pathlib import Path
import sys
import os
from django.core.exceptions import ImproperlyConfigured

import dj_database_url
from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Load environment variables from .env for local/dev reliability.
load_dotenv(BASE_DIR / '.env')

# Optional local overrides (ignored by git). Useful when `.env` is production.
load_dotenv(BASE_DIR / '.env.local', override=True)

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
DEFAULT_SECRET_KEY = 'django-insecure-xp^wz=i&8%o*%@2)7#k-7w7fhxcxgxq(4kw)nkc$#oj&6d^xp9'
SECRET_KEY = os.getenv('SECRET_KEY', DEFAULT_SECRET_KEY)

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv('DEBUG', 'True').lower() == 'true'

ENVIRONMENT = os.getenv('ENVIRONMENT', 'development').strip().lower()
IS_PRODUCTION = ENVIRONMENT in {'production', 'prod'}

ALLOWED_HOSTS = [
    host.strip()
    for host in os.getenv('ALLOWED_HOSTS', '127.0.0.1,localhost,testserver').split(',')
    if host.strip()
]

if IS_PRODUCTION:
    if DEBUG:
        raise ImproperlyConfigured('DEBUG must be False when ENVIRONMENT=production.')
    if SECRET_KEY == DEFAULT_SECRET_KEY or SECRET_KEY.startswith('django-insecure-'):
        raise ImproperlyConfigured('Set a strong SECRET_KEY for production environment.')
    if not ALLOWED_HOSTS:
        raise ImproperlyConfigured('ALLOWED_HOSTS must be configured for production environment.')


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'blood.apps.BloodConfig',
    'donor.apps.DonorConfig',
    'patient',
    'widget_tweaks',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'bloodbankmanagement.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [
            os.path.join(BASE_DIR, 'templates'),
            os.path.join(BASE_DIR, 'templates/blood'),
            os.path.join(BASE_DIR, 'templates/donor'),
            os.path.join(BASE_DIR, 'templates/patient'),
        ],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'bloodbankmanagement.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

DATABASES = {
    'default': dj_database_url.config(
        default=f"sqlite:///{BASE_DIR / 'db.sqlite3'}",
        conn_max_age=600
    )
}

# Optional secondary database used for one-time imports (e.g., bundled demo SQLite -> Postgres).
legacy_database_url = os.getenv('LEGACY_DATABASE_URL', '').strip()
if legacy_database_url:
    DATABASES['legacy'] = dj_database_url.parse(legacy_database_url, conn_max_age=0)


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'en'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'
STATICFILES_DIRS = [
    BASE_DIR / 'static',
]

# In production we prefer WhiteNoise + hashed manifest files.
# However, if the staticfiles manifest doesn't exist yet (common in local runs
# when `.env` is set to production), fall back to non-manifest storage so
# `{% static %}` can still resolve assets like the homepage background.
_static_manifest_path = STATIC_ROOT / 'staticfiles.json'
_running_collectstatic = len(sys.argv) > 1 and sys.argv[1] == 'collectstatic'
USE_MANIFEST_STATICFILES = IS_PRODUCTION and (_running_collectstatic or _static_manifest_path.exists())

STATICFILES_STORAGE = (
    'whitenoise.storage.CompressedManifestStaticFilesStorage'
    if USE_MANIFEST_STATICFILES
    else 'django.contrib.staticfiles.storage.StaticFilesStorage'
)

# When not using the manifest storage, let WhiteNoise resolve files via finders.
WHITENOISE_USE_FINDERS = not USE_MANIFEST_STATICFILES

# Media files
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Login URLs
LOGIN_URL = '/adminlogin/'
LOGIN_REDIRECT_URL = '/afterlogin/'

# Messages framework
from django.contrib.messages import constants as messages
MESSAGE_TAGS = {
    messages.DEBUG: 'debug',
    messages.INFO: 'info',
    messages.SUCCESS: 'success',
    messages.WARNING: 'warning',
    messages.ERROR: 'danger',
}

# File upload settings
FILE_UPLOAD_MAX_MEMORY_SIZE = 5242880  # 5MB
DATA_UPLOAD_MAX_MEMORY_SIZE = 5242880  # 5MB

# Security settings for development
SECURE_BROWSER_XSS_FILTER = True
SECURE_CONTENT_TYPE_NOSNIFF = True
X_FRAME_OPTIONS = 'DENY'

# Session settings
SESSION_COOKIE_AGE = 3600  # 1 hour
SESSION_EXPIRE_AT_BROWSER_CLOSE = True

# Logging configuration
# NOTE: SQL logging is very noisy; keep it opt-in.
LOG_SQL = os.getenv('LOG_SQL', 'false').lower() == 'true'
LOG_TO_FILE = os.getenv('LOG_TO_FILE', 'false').lower() == 'true'
LOG_FILE_PATH = os.getenv('LOG_FILE_PATH', str(BASE_DIR / 'logs' / 'django.log'))

if LOG_TO_FILE:
    os.makedirs(os.path.dirname(LOG_FILE_PATH), exist_ok=True)

logging_handlers = {
    'console': {
        'class': 'logging.StreamHandler',
    },
}

if LOG_TO_FILE:
    logging_handlers['file'] = {
        'class': 'logging.FileHandler',
        'filename': LOG_FILE_PATH,
        'level': 'INFO',
    }

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'handlers': logging_handlers,
    'root': {
        'handlers': ['console'] + (['file'] if LOG_TO_FILE else []),
        'level': 'INFO',
    },
    'loggers': {
        'django.db.backends': {
            'handlers': ['console'] + (['file'] if LOG_TO_FILE else []),
            'level': 'DEBUG' if LOG_SQL else 'INFO',
            'propagate': False,
        },
    },
}

# Geocoding defaults
GEOCODER_ALLOW_REMOTE = os.getenv('GEOCODER_ALLOW_REMOTE', 'true').lower() == 'true'
GEOCODER_COUNTRY_BIAS = os.getenv('GEOCODER_COUNTRY_BIAS', 'in') or None
GEOCODER_USER_AGENT = os.getenv('GEOCODER_USER_AGENT', 'bloodbridge-geocoder')
GEOCODER_TIMEOUT = int(os.getenv('GEOCODER_TIMEOUT', '10'))
GEOCODER_MIN_DELAY_SECONDS = float(os.getenv('GEOCODER_MIN_DELAY_SECONDS', '1.0'))
GEOCODER_STATIC_FIXTURES = {
    '221b baker street': (51.523771, -0.158539),
    'test address': (12.971599, 77.594566),
    'delhi, india': (28.613939, 77.209023),
    'mumbai, india': (19.076090, 72.877426),
}

# AWS SNS configuration for urgent SMS alerts
AWS_SNS_ENABLED = os.getenv('AWS_SNS_ENABLED', 'false').lower() == 'true'
AWS_SNS_REGION = os.getenv('AWS_SNS_REGION', 'ap-south-1')
AWS_SNS_DEFAULT_COUNTRY_CODE = os.getenv('AWS_SNS_DEFAULT_COUNTRY_CODE', '+91')
AWS_SNS_SENDER_ID = os.getenv('AWS_SNS_SENDER_ID', None)
# In India (+91), SenderID often requires DLT registration; using an unregistered
# sender can lead to silent non-delivery even when SNS returns a MessageId.
# Default: ignore AWS_SNS_SENDER_ID unless explicitly allowed.
AWS_SNS_ALLOW_SENDER_ID = os.getenv('AWS_SNS_ALLOW_SENDER_ID', 'false').lower() == 'true'
if (not AWS_SNS_ALLOW_SENDER_ID) and str(AWS_SNS_DEFAULT_COUNTRY_CODE).strip().startswith('+91'):
    AWS_SNS_SENDER_ID = None
# 0 means unlimited recipients per urgent broadcast.
AWS_SNS_MAX_RECIPIENTS = int(os.getenv('AWS_SNS_MAX_RECIPIENTS', '0'))
AWS_SNS_MIN_NOTIFICATION_GAP_SECONDS = int(os.getenv('AWS_SNS_MIN_NOTIFICATION_GAP_SECONDS', '1800'))
AWS_SNS_SMS_TYPE = os.getenv('AWS_SNS_SMS_TYPE', 'Transactional')

# When True (dev default), OTP codes and welcome messages are printed to the
# server console if the SMS provider fails or is disabled.  The OTP is also
# shown in the browser flash message so developers can test without real SMS.
SMS_CONSOLE_FALLBACK = os.getenv('SMS_CONSOLE_FALLBACK', str(DEBUG)).lower() == 'true'

# ─── Amazon SageMaker Donor Recommendation AI ────────────────────────────────
# When enabled, the donor recommendation page calls a SageMaker endpoint to
# produce an ML-driven score (0–100) for each donor. When disabled or unreachable,
# the system falls back to a deterministic heuristic that mimics the model weights.
SAGEMAKER_ENDPOINT_ENABLED = os.getenv('SAGEMAKER_ENDPOINT_ENABLED', 'false').lower() == 'true'
SAGEMAKER_ENDPOINT_NAME = os.getenv('SAGEMAKER_ENDPOINT_NAME', 'bloodbridge-donor-recommender')
SAGEMAKER_REGION = os.getenv('SAGEMAKER_REGION', os.getenv('AWS_SNS_REGION', 'ap-south-1'))

# Celery (background jobs)
# Recommended broker: Redis. On Windows, run workers with --pool=solo.
CELERY_BROKER_URL = os.getenv('CELERY_BROKER_URL', 'redis://localhost:6379/0')
CELERY_RESULT_BACKEND = os.getenv('CELERY_RESULT_BACKEND', CELERY_BROKER_URL)
CELERY_ACCEPT_CONTENT = ['json']
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'
CELERY_TIMEZONE = TIME_ZONE

# Development/testing helper: run tasks inline without a worker.
# Cloud Run demo default: if CELERY_TASK_ALWAYS_EAGER isn't explicitly set, run inline.
celery_task_always_eager_env = os.getenv('CELERY_TASK_ALWAYS_EAGER')
if celery_task_always_eager_env is None and os.getenv('K_SERVICE'):
    CELERY_TASK_ALWAYS_EAGER = True
else:
    CELERY_TASK_ALWAYS_EAGER = (celery_task_always_eager_env or 'false').lower() == 'true'

# Admin UI: show/hide the SMS mode banner (broker health / eager mode).
# Default: hidden to avoid noisy warnings in local setups without Redis.
ADMIN_SHOW_SMS_MODE_BANNER = os.getenv('ADMIN_SHOW_SMS_MODE_BANNER', 'false').lower() == 'true'

FORCE_HTTPS = os.getenv('FORCE_HTTPS', 'true' if IS_PRODUCTION else 'false').lower() == 'true'

if (IS_PRODUCTION or not DEBUG) and FORCE_HTTPS:
    # When running behind a proxy (Cloud Run, load balancers), respect forwarded HTTPS scheme.
    SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')

    csrf_trusted_origins_env = os.getenv('CSRF_TRUSTED_ORIGINS', '').strip()
    if csrf_trusted_origins_env:
        CSRF_TRUSTED_ORIGINS = [
            origin.strip()
            for origin in csrf_trusted_origins_env.split(',')
            if origin.strip()
        ]
    else:
        # Derive safe defaults from ALLOWED_HOSTS.
        # If a host begins with a dot (e.g. `.a.run.app`), turn it into a wildcard origin.
        derived = []
        for host in ALLOWED_HOSTS:
            if host in ('127.0.0.1', 'localhost', 'testserver', '*'):
                continue
            if host.startswith('.'):
                derived.append('https://*' + host)
            else:
                derived.append('https://' + host)
        CSRF_TRUSTED_ORIGINS = derived

    SECURE_SSL_REDIRECT = True
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    SECURE_HSTS_SECONDS = 31536000
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True


