# Generated by Django 5.2.8 on 2026-01-19 15:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blood', '0011_bloodrequest_sms_last_approval_attempt_at_and_more'),
        ('donor', '0006_backfill_last_donated_at'),
        ('patient', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_type', models.CharField(choices=[('DONOR', 'Donor'), ('PATIENT', 'Patient'), ('ANONYMOUS', 'Anonymous')], default='ANONYMOUS', max_length=16)),
                ('display_name', models.CharField(blank=True, max_length=60)),
                ('feedback_for', models.CharField(choices=[('DONATION', 'Donation'), ('REQUEST', 'Request'), ('GENERAL', 'General')], default='GENERAL', max_length=16)),
                ('rating', models.PositiveSmallIntegerField(default=5)),
                ('message', models.TextField(max_length=1200)),
                ('image1', models.ImageField(blank=True, null=True, upload_to='feedback/%Y/%m/')),
                ('image2', models.ImageField(blank=True, null=True, upload_to='feedback/%Y/%m/')),
                ('image3', models.ImageField(blank=True, null=True, upload_to='feedback/%Y/%m/')),
                ('is_public', models.BooleanField(default=True)),
                ('admin_reaction', models.CharField(blank=True, choices=[('', '—'), ('👍', '👍'), ('❤️', '❤️'), ('🙏', '🙏'), ('👏', '👏'), ('😊', '😊'), ('🎉', '🎉')], max_length=8)),
                ('admin_reply', models.TextField(blank=True, max_length=1200)),
                ('admin_updated_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('donor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='donor.donor')),
                ('patient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='patient.patient')),
            ],
            options={
                'ordering': ['-created_at'],
                'constraints': [models.CheckConstraint(check=models.Q(('donor__isnull', False), ('patient__isnull', False), _negated=True), name='feedback_not_both_donor_and_patient'), models.CheckConstraint(check=models.Q(models.Q(('author_type', 'ANONYMOUS'), ('donor__isnull', True), ('patient__isnull', True)), models.Q(('author_type', 'DONOR'), ('donor__isnull', False), ('patient__isnull', True)), models.Q(('author_type', 'PATIENT'), ('donor__isnull', True), ('patient__isnull', False)), _connector='OR'), name='feedback_author_matches_fk'), models.CheckConstraint(check=models.Q(('rating__gte', 1), ('rating__lte', 5)), name='feedback_rating_1_to_5')],
            },
        ),
    ]
