# Generated by Django 4.1.13 on 2026-03-07 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blood', '0017_password_reset_otp'),
    ]

    operations = [
        migrations.AddField(
            model_name='bloodrequest',
            name='doctor_prescription',
            field=models.FileField(blank=True, help_text='Upload doctor prescription for this blood request', null=True, upload_to='prescriptions/requests/%Y/%m/'),
        ),
    ]
