# Generated by Django 4.1.13 on 2025-11-30 11:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('donor', '0004_donor_availability_updated_at_donor_is_available_and_more'),
        ('blood', '0005_auto_20251015_2046'),
    ]

    operations = [
        migrations.AddField(
            model_name='bloodrequest',
            name='is_urgent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='bloodrequest',
            name='request_zipcode',
            field=models.CharField(blank=True, max_length=12),
        ),
        migrations.CreateModel(
            name='MatchAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Confirmed', 'Confirmed'), ('Declined', 'Declined'), ('Expired', 'Expired')], default='Pending', max_length=10)),
                ('confirmation_token', models.CharField(default='50017948880e4e6ca0ea5a25867ac2e7', max_length=64, unique=True)),
                ('zipcode_match_score', models.PositiveSmallIntegerField(default=0)),
                ('sent_via_sms', models.BooleanField(default=False)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('responded_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('donor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='match_alerts', to='donor.donor')),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='match_alerts', to='blood.bloodrequest')),
            ],
        ),
        migrations.AddIndex(
            model_name='matchalert',
            index=models.Index(fields=['status'], name='blood_match_status_8f82b9_idx'),
        ),
        migrations.AddIndex(
            model_name='matchalert',
            index=models.Index(fields=['request', 'status'], name='blood_match_request_eefd7b_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='matchalert',
            unique_together={('request', 'donor')},
        ),
    ]
