# Generated by Django 5.2.8 on 2026-01-16 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blood', '0010_alter_bloodrequest_patient_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bloodrequest',
            name='sms_last_approval_attempt_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bloodrequest',
            name='sms_last_approval_donor_to',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name='bloodrequest',
            name='sms_last_approval_patient_to',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name='bloodrequest',
            name='sms_last_approval_result',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
